# -*- coding: utf-8 -*-
"""MOJE YOLO_pro5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cUAJAFI-kPRmbq8H-j6OxCN2gy9odiak

https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/
"""

# Commented out IPython magic to ensure Python compatibility.

import torch
import utils

# git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

display = utils.notebook_init()  # checks

# pip install -r yolov5/requirements.txt

"""*   Wrzucić pliki .yaml do Data
*   Wrzucić datasety do głównego folderu

# Rozpakowanie paczek z datasetami
"""

# unzip -q ../train_data.zip -d ../

# unzip -q ../train_data_cars.zip -d ../

"""# Trenowanie gotowych modeli"""

# python train.py --img 640 --batch 16 --epochs 30 --data custom_car_data.yaml --weights yolov5s.pt

# python yolov5/train.py --img 640 --batch 16 --epochs 50 --data custom_data.yaml --weights yolov5s.pt

# python yolov5/detect.py --source kruy_andre_t.mp4

# python yolov5/detect.py --weights runs/train/exp4/weights/last.pt --source kruy_andre_t.mp4

"""# zad 1
Przygotuj zbiór danych z minimum 4 kategoriami. Z każdej kategori ma być minimum 10 przykładów i w sumie ma być minimum 20 zdjęć. Z zaznaczeniem że jeśli zdjęcia są z jednego filmu lub jednej sytuacji, czyli mają podobne oświetlenie, to przykłądów powinno być minimum 2 razy więcej.

# zad 2
Wybierz odpowiedni dla siebie model i wytrenuj na losowych wagach oraz na juz wytrenowanych.

# zad 3
Wykonaj detekcję obydwu modeli na przykładowym filmie i porównaj rezultaty.
"""